[SETTINGS]
# .   for same directory
output_path = %%USERPROFILE%%\Documents\Übersetzte Powerpoint Präsentationen\
target_lang = EN-GB
deepl_api_key = 340c043e-c507-fffd-3284-58f3b6d4c1cd
[DEVELOPMENT]
use_deepl_api = True
marker_char = +